### ISSUE TITLE
Crash on start - k8s based

### ISSUE THREAD

**Issue by f3rn0s** [commjoen/wrongsecrets#203]
I spun up the project in a default k8s environment following the steps here:

```bash
    kubectl apply -f k8s/secrets-config.yml
    kubectl apply -f k8s/secrets-secret.yml
    kubectl apply -f k8s/secret-challenge-deployment.yml
    while [[ $(kubectl get pods -l app=secret-challenge -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for secret-challenge" && sleep 2; done
    kubectl port-forward \
        $(kubectl get pod -l app=secret-challenge -o jsonpath="{.items[0].metadata.name}") \
        8080:8080
```

But the pod fails to boot:

```text
$ kubectl logs secret-challenge-55794fbc7-zgff9

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.3)

2022-02-18 01:28:02.674  INFO 9 --- [           main] o.o.w.WrongSecretsApplication            : Starting WrongSecretsApplication v1.3.4C-SNAPSHOT using Java 17 on secret-challenge-55794fbc7-zgff9 with PID 9 (
/application.jar started by wrongsecrets in /)
2022-02-18 01:28:02.675  INFO 9 --- [           main] o.o.w.WrongSecretsApplication            : The following profiles are active: without-vault
2022-02-18 01:28:03.512  INFO 9 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=01332596-1b4a-37af-932e-0d89f4cbb45c
2022-02-18 01:28:03.832  INFO 9 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-02-18 01:28:03.840  INFO 9 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-02-18 01:28:03.840  INFO 9 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.56]
2022-02-18 01:28:03.895  INFO 9 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-02-18 01:28:03.896  INFO 9 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1037 ms
2022-02-18 01:28:04.128  WARN 9 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.fact
ory.BeanCreationException: Error creating bean with name 'runtimeEnvironment' defined in URL [jar:file:/application.jar!/BOOT-INF/classes!/org/owasp/wrongsecrets/RuntimeEnvironment.class]: Bean instantiation v
ia constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.owasp.wrongsecrets.RuntimeEnvironment]: Constructor threw exception; nested exception
 is java.util.NoSuchElementException: No value present
2022-02-18 01:28:04.130  INFO 9 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-02-18 01:28:04.146  INFO 9 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-02-18 01:28:04.160 ERROR 9 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'runtimeEnvironment' defined in URL [jar:file:/application.jar!/BOOT-INF/classes!/org/owasp/wrongsecrets/RuntimeEnvironmen
t.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.owasp.wrongsecrets.RuntimeEnvironment]: Constructor thr
ew exception; nested exception is java.util.NoSuchElementException: No value present
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.15.jar!/:5.3.15]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.15.jar!/:5.3.15]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.owasp.wrongsecrets.WrongSecretsApplication.main(WrongSecretsApplication.java:16) ~[classes!/:1.3.4C-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application.jar:1.3.4C-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[application.jar:1.3.4C-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application.jar:1.3.4C-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[application.jar:1.3.4C-SNAPSHOT]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.owasp.wrongsecrets.RuntimeEnvironment]: Constructor threw exception; nested exception is java.util.NoSuchElementExcep
tion: No value present
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.15.jar!/:5.3.15]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.15.jar!/:5.3.15]
        ... 27 common frames omitted
Caused by: java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:143) ~[na:na]
        at org.owasp.wrongsecrets.RuntimeEnvironment$Environment.fromId(RuntimeEnvironment.java:45) ~[classes!/:1.3.4C-SNAPSHOT]
        at org.owasp.wrongsecrets.RuntimeEnvironment.<init>(RuntimeEnvironment.java:54) ~[classes!/:1.3.4C-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.15.jar!/:5.3.15]
        ... 29 common frames omitted
```

**Comment by f3rn0s** [comment]
All of the YAML files look like they have been applied:

```bash
$ kubectl get configmaps
NAME               DATA   AGE
kube-root-ca.crt   1      20h
secrets-file       1      12m
$ kubectl get deployments
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
secret-challenge   0/1     1            0           12m
$ kubectl get secrets
NAME                  TYPE                                  DATA   AGE
default-token-l8nml   kubernetes.io/service-account-token   3      20h
funnystuff            Opaque                                1      12m
```

**Comment by f3rn0s** [comment]
Looks like this issue potentially stems from an invalid ENV entry:

```
            - name: K8S_ENV
              value: k8s-without-vault
```

Which does not match any of the expected values in the enum in RuntimeEnvironment.java:

```
DOCKER("Docker"), HEROKU_DOCKER("Heroku(Docker)"), GCP("gcp"), AWS("aws"), AZURE("azure"), VAULT("k8s-with-vault"), K8S("k8s");
```

**Comment by commjoen** [comment]
Thank you very much for your issue! Looks like you found a solution as well. I will investigate it today.


I am very sorry for not testing the k8s variant without vault on every release, so we did not catch it, so I will add some basic GitHub action after this.

I would like to mention you as a contributor if the pr is correct. What name can I add next to your GitHub handle? (Eg which first/last name)

**Comment by commjoen** [comment]
Please let us know how we can attribute the fix to you :) and then we can close this down.

**Comment by f3rn0s** [comment]
Finn (@f3rn0s) is fine @commjoen

**Comment by commjoen** [comment]
Will be in place with https://github.com/commjoen/wrongsecrets/pull/205 :) Once merged, we can close this issue.
Again, thank you for spotting the issue and providing a swift repair :)
